from .addstickertoset import addStickerToSet
from .affiliateinfo import AffiliateInfo
from .animation import Animation
from .answercallbackquery import answerCallbackQuery
from .answerinlinequery import answerInlineQuery
from .answerprecheckoutquery import answerPreCheckoutQuery
from .answershippingquery import answerShippingQuery
from .answerwebappquery import answerWebAppQuery
from .approvechatjoinrequest import approveChatJoinRequest
from .audio import Audio
from .backgroundfill import BackgroundFill
from .backgroundfillfreeformgradient import BackgroundFillFreeformGradient
from .backgroundfillgradient import BackgroundFillGradient
from .backgroundfillsolid import BackgroundFillSolid
from .backgroundtype import BackgroundType
from .backgroundtypechattheme import BackgroundTypeChatTheme
from .backgroundtypefill import BackgroundTypeFill
from .backgroundtypepattern import BackgroundTypePattern
from .backgroundtypewallpaper import BackgroundTypeWallpaper
from .banchatmember import banChatMember
from .banchatsenderchat import banChatSenderChat
from .birthdate import Birthdate
from .botcommand import BotCommand
from .botcommandscope import BotCommandScope
from .botcommandscopeallchatadministrators import BotCommandScopeAllChatAdministrators
from .botcommandscopeallgroupchats import BotCommandScopeAllGroupChats
from .botcommandscopeallprivatechats import BotCommandScopeAllPrivateChats
from .botcommandscopechat import BotCommandScopeChat
from .botcommandscopechatadministrators import BotCommandScopeChatAdministrators
from .botcommandscopechatmember import BotCommandScopeChatMember
from .botcommandscopedefault import BotCommandScopeDefault
from .botdescription import BotDescription
from .botname import BotName
from .botshortdescription import BotShortDescription
from .businessconnection import BusinessConnection
from .businessintro import BusinessIntro
from .businesslocation import BusinessLocation
from .businessmessagesdeleted import BusinessMessagesDeleted
from .businessopeninghours import BusinessOpeningHours
from .businessopeninghoursinterval import BusinessOpeningHoursInterval
from .callbackgame import CallbackGame
from .callbackquery import CallbackQuery
from .chat import Chat
from .chatadministratorrights import ChatAdministratorRights
from .chatbackground import ChatBackground
from .chatboost import ChatBoost
from .chatboostadded import ChatBoostAdded
from .chatboostremoved import ChatBoostRemoved
from .chatboostsource import ChatBoostSource
from .chatboostsourcegiftcode import ChatBoostSourceGiftCode
from .chatboostsourcegiveaway import ChatBoostSourceGiveaway
from .chatboostsourcepremium import ChatBoostSourcePremium
from .chatboostupdated import ChatBoostUpdated
from .chatfullinfo import ChatFullInfo
from .chatinvitelink import ChatInviteLink
from .chatjoinrequest import ChatJoinRequest
from .chatlocation import ChatLocation
from .chatmember import ChatMember
from .chatmemberadministrator import ChatMemberAdministrator
from .chatmemberbanned import ChatMemberBanned
from .chatmemberleft import ChatMemberLeft
from .chatmembermember import ChatMemberMember
from .chatmemberowner import ChatMemberOwner
from .chatmemberrestricted import ChatMemberRestricted
from .chatmemberupdated import ChatMemberUpdated
from .chatpermissions import ChatPermissions
from .chatphoto import ChatPhoto
from .chatshared import ChatShared
from .choseninlineresult import ChosenInlineResult
from .close import close
from .closeforumtopic import closeForumTopic
from .closegeneralforumtopic import closeGeneralForumTopic
from .contact import Contact
from .copymessage import copyMessage
from .copymessages import copyMessages
from .copytextbutton import CopyTextButton
from .createchatinvitelink import createChatInviteLink
from .createchatsubscriptioninvitelink import createChatSubscriptionInviteLink
from .createforumtopic import createForumTopic
from .createinvoicelink import createInvoiceLink
from .createnewstickerset import createNewStickerSet
from .declinechatjoinrequest import declineChatJoinRequest
from .deletechatphoto import deleteChatPhoto
from .deletechatstickerset import deleteChatStickerSet
from .deleteforumtopic import deleteForumTopic
from .deletemessage import deleteMessage
from .deletemessages import deleteMessages
from .deletemycommands import deleteMyCommands
from .deletestickerfromset import deleteStickerFromSet
from .deletestickerset import deleteStickerSet
from .deletewebhook import deleteWebhook
from .dice import Dice
from .document import Document
from .editchatinvitelink import editChatInviteLink
from .editchatsubscriptioninvitelink import editChatSubscriptionInviteLink
from .editforumtopic import editForumTopic
from .editgeneralforumtopic import editGeneralForumTopic
from .editmessagecaption import editMessageCaption
from .editmessagelivelocation import editMessageLiveLocation
from .editmessagemedia import editMessageMedia
from .editmessagereplymarkup import editMessageReplyMarkup
from .editmessagetext import editMessageText
from .edituserstarsubscription import editUserStarSubscription
from .encryptedcredentials import EncryptedCredentials
from .encryptedpassportelement import EncryptedPassportElement
from .exportchatinvitelink import exportChatInviteLink
from .externalreplyinfo import ExternalReplyInfo
from .file import File
from .forcereply import ForceReply
from .forumtopic import ForumTopic
from .forumtopicclosed import ForumTopicClosed
from .forumtopiccreated import ForumTopicCreated
from .forumtopicedited import ForumTopicEdited
from .forumtopicreopened import ForumTopicReopened
from .forwardmessage import forwardMessage
from .forwardmessages import forwardMessages
from .game import Game
from .gamehighscore import GameHighScore
from .generalforumtopichidden import GeneralForumTopicHidden
from .generalforumtopicunhidden import GeneralForumTopicUnhidden
from .getavailablegifts import getAvailableGifts
from .getbusinessconnection import getBusinessConnection
from .getchat import getChat
from .getchatadministrators import getChatAdministrators
from .getchatmember import getChatMember
from .getchatmembercount import getChatMemberCount
from .getchatmenubutton import getChatMenuButton
from .getcustomemojistickers import getCustomEmojiStickers
from .getfile import getFile
from .getforumtopiciconstickers import getForumTopicIconStickers
from .getgamehighscores import getGameHighScores
from .getme import getMe
from .getmycommands import getMyCommands
from .getmydefaultadministratorrights import getMyDefaultAdministratorRights
from .getmydescription import getMyDescription
from .getmyname import getMyName
from .getmyshortdescription import getMyShortDescription
from .getstartransactions import getStarTransactions
from .getstickerset import getStickerSet
from .getupdates import getUpdates
from .getuserchatboosts import getUserChatBoosts
from .getuserprofilephotos import getUserProfilePhotos
from .getwebhookinfo import getWebhookInfo
from .gift import Gift
from .gifts import Gifts
from .giveaway import Giveaway
from .giveawaycompleted import GiveawayCompleted
from .giveawaycreated import GiveawayCreated
from .giveawaywinners import GiveawayWinners
from .hidegeneralforumtopic import hideGeneralForumTopic
from .inaccessiblemessage import InaccessibleMessage
from .inlinekeyboardbutton import InlineKeyboardButton
from .inlinekeyboardmarkup import InlineKeyboardMarkup
from .inlinequery import InlineQuery
from .inlinequeryresult import InlineQueryResult
from .inlinequeryresultarticle import InlineQueryResultArticle
from .inlinequeryresultaudio import InlineQueryResultAudio
from .inlinequeryresultcachedaudio import InlineQueryResultCachedAudio
from .inlinequeryresultcacheddocument import InlineQueryResultCachedDocument
from .inlinequeryresultcachedgif import InlineQueryResultCachedGif
from .inlinequeryresultcachedmpeg4gif import InlineQueryResultCachedMpeg4Gif
from .inlinequeryresultcachedphoto import InlineQueryResultCachedPhoto
from .inlinequeryresultcachedsticker import InlineQueryResultCachedSticker
from .inlinequeryresultcachedvideo import InlineQueryResultCachedVideo
from .inlinequeryresultcachedvoice import InlineQueryResultCachedVoice
from .inlinequeryresultcontact import InlineQueryResultContact
from .inlinequeryresultdocument import InlineQueryResultDocument
from .inlinequeryresultgame import InlineQueryResultGame
from .inlinequeryresultgif import InlineQueryResultGif
from .inlinequeryresultlocation import InlineQueryResultLocation
from .inlinequeryresultmpeg4gif import InlineQueryResultMpeg4Gif
from .inlinequeryresultphoto import InlineQueryResultPhoto
from .inlinequeryresultsbutton import InlineQueryResultsButton
from .inlinequeryresultvenue import InlineQueryResultVenue
from .inlinequeryresultvideo import InlineQueryResultVideo
from .inlinequeryresultvoice import InlineQueryResultVoice
from .inputcontactmessagecontent import InputContactMessageContent
from .inputinvoicemessagecontent import InputInvoiceMessageContent
from .inputlocationmessagecontent import InputLocationMessageContent
from .inputmedia import InputMedia
from .inputmediaanimation import InputMediaAnimation
from .inputmediaaudio import InputMediaAudio
from .inputmediadocument import InputMediaDocument
from .inputmediaphoto import InputMediaPhoto
from .inputmediavideo import InputMediaVideo
from .inputmessagecontent import InputMessageContent
from .inputpaidmedia import InputPaidMedia
from .inputpaidmediaphoto import InputPaidMediaPhoto
from .inputpaidmediavideo import InputPaidMediaVideo
from .inputpolloption import InputPollOption
from .inputsticker import InputSticker
from .inputtextmessagecontent import InputTextMessageContent
from .inputvenuemessagecontent import InputVenueMessageContent
from .invoice import Invoice
from .keyboardbutton import KeyboardButton
from .keyboardbuttonpolltype import KeyboardButtonPollType
from .keyboardbuttonrequestchat import KeyboardButtonRequestChat
from .keyboardbuttonrequestusers import KeyboardButtonRequestUsers
from .labeledprice import LabeledPrice
from .leavechat import leaveChat
from .linkpreviewoptions import LinkPreviewOptions
from .location import Location
from .loginurl import LoginUrl
from .logout import logOut
from .maskposition import MaskPosition
from .maybeinaccessiblemessage import MaybeInaccessibleMessage
from .menubutton import MenuButton
from .menubuttoncommands import MenuButtonCommands
from .menubuttondefault import MenuButtonDefault
from .menubuttonwebapp import MenuButtonWebApp
from .message import Message
from .messageautodeletetimerchanged import MessageAutoDeleteTimerChanged
from .messageentity import MessageEntity
from .messageid import MessageId
from .messageorigin import MessageOrigin
from .messageoriginchannel import MessageOriginChannel
from .messageoriginchat import MessageOriginChat
from .messageoriginhiddenuser import MessageOriginHiddenUser
from .messageoriginuser import MessageOriginUser
from .messagereactioncountupdated import MessageReactionCountUpdated
from .messagereactionupdated import MessageReactionUpdated
from .orderinfo import OrderInfo
from .paidmedia import PaidMedia
from .paidmediainfo import PaidMediaInfo
from .paidmediaphoto import PaidMediaPhoto
from .paidmediapreview import PaidMediaPreview
from .paidmediapurchased import PaidMediaPurchased
from .paidmediavideo import PaidMediaVideo
from .passportdata import PassportData
from .passportelementerror import PassportElementError
from .passportelementerrordatafield import PassportElementErrorDataField
from .passportelementerrorfile import PassportElementErrorFile
from .passportelementerrorfiles import PassportElementErrorFiles
from .passportelementerrorfrontside import PassportElementErrorFrontSide
from .passportelementerrorreverseside import PassportElementErrorReverseSide
from .passportelementerrorselfie import PassportElementErrorSelfie
from .passportelementerrortranslationfile import PassportElementErrorTranslationFile
from .passportelementerrortranslationfiles import PassportElementErrorTranslationFiles
from .passportelementerrorunspecified import PassportElementErrorUnspecified
from .passportfile import PassportFile
from .photosize import PhotoSize
from .pinchatmessage import pinChatMessage
from .poll import Poll
from .pollanswer import PollAnswer
from .polloption import PollOption
from .precheckoutquery import PreCheckoutQuery
from .preparedinlinemessage import PreparedInlineMessage
from .promotechatmember import promoteChatMember
from .proximityalerttriggered import ProximityAlertTriggered
from .reactioncount import ReactionCount
from .reactiontype import ReactionType
from .reactiontypecustomemoji import ReactionTypeCustomEmoji
from .reactiontypeemoji import ReactionTypeEmoji
from .reactiontypepaid import ReactionTypePaid
from .refundedpayment import RefundedPayment
from .refundstarpayment import refundStarPayment
from .removechatverification import removeChatVerification
from .removeuserverification import removeUserVerification
from .reopenforumtopic import reopenForumTopic
from .reopengeneralforumtopic import reopenGeneralForumTopic
from .replacestickerinset import replaceStickerInSet
from .replykeyboardmarkup import ReplyKeyboardMarkup
from .replykeyboardremove import ReplyKeyboardRemove
from .replyparameters import ReplyParameters
from .responseparameters import ResponseParameters
from .restrictchatmember import restrictChatMember
from .revenuewithdrawalstate import RevenueWithdrawalState
from .revenuewithdrawalstatefailed import RevenueWithdrawalStateFailed
from .revenuewithdrawalstatepending import RevenueWithdrawalStatePending
from .revenuewithdrawalstatesucceeded import RevenueWithdrawalStateSucceeded
from .revokechatinvitelink import revokeChatInviteLink
from .savepreparedinlinemessage import savePreparedInlineMessage
from .sendanimation import sendAnimation
from .sendaudio import sendAudio
from .sendchataction import sendChatAction
from .sendcontact import sendContact
from .senddice import sendDice
from .senddocument import sendDocument
from .sendgame import sendGame
from .sendgift import sendGift
from .sendinvoice import sendInvoice
from .sendlocation import sendLocation
from .sendmediagroup import sendMediaGroup
from .sendmessage import sendMessage
from .sendpaidmedia import sendPaidMedia
from .sendphoto import sendPhoto
from .sendpoll import sendPoll
from .sendsticker import sendSticker
from .sendvenue import sendVenue
from .sendvideo import sendVideo
from .sendvideonote import sendVideoNote
from .sendvoice import sendVoice
from .sentwebappmessage import SentWebAppMessage
from .setchatadministratorcustomtitle import setChatAdministratorCustomTitle
from .setchatdescription import setChatDescription
from .setchatmenubutton import setChatMenuButton
from .setchatpermissions import setChatPermissions
from .setchatphoto import setChatPhoto
from .setchatstickerset import setChatStickerSet
from .setchattitle import setChatTitle
from .setcustomemojistickersetthumbnail import setCustomEmojiStickerSetThumbnail
from .setgamescore import setGameScore
from .setmessagereaction import setMessageReaction
from .setmycommands import setMyCommands
from .setmydefaultadministratorrights import setMyDefaultAdministratorRights
from .setmydescription import setMyDescription
from .setmyname import setMyName
from .setmyshortdescription import setMyShortDescription
from .setpassportdataerrors import setPassportDataErrors
from .setstickeremojilist import setStickerEmojiList
from .setstickerkeywords import setStickerKeywords
from .setstickermaskposition import setStickerMaskPosition
from .setstickerpositioninset import setStickerPositionInSet
from .setstickersetthumbnail import setStickerSetThumbnail
from .setstickersettitle import setStickerSetTitle
from .setuseremojistatus import setUserEmojiStatus
from .setwebhook import setWebhook
from .shareduser import SharedUser
from .shippingaddress import ShippingAddress
from .shippingoption import ShippingOption
from .shippingquery import ShippingQuery
from .startransaction import StarTransaction
from .startransactions import StarTransactions
from .sticker import Sticker
from .stickerset import StickerSet
from .stopmessagelivelocation import stopMessageLiveLocation
from .stoppoll import stopPoll
from .story import Story
from .successfulpayment import SuccessfulPayment
from .switchinlinequerychosenchat import SwitchInlineQueryChosenChat
from .textquote import TextQuote
from .transactionpartner import TransactionPartner
from .transactionpartneraffiliateprogram import TransactionPartnerAffiliateProgram
from .transactionpartnerfragment import TransactionPartnerFragment
from .transactionpartnerother import TransactionPartnerOther
from .transactionpartnertelegramads import TransactionPartnerTelegramAds
from .transactionpartnertelegramapi import TransactionPartnerTelegramApi
from .transactionpartneruser import TransactionPartnerUser
from .unbanchatmember import unbanChatMember
from .unbanchatsenderchat import unbanChatSenderChat
from .unhidegeneralforumtopic import unhideGeneralForumTopic
from .unpinallchatmessages import unpinAllChatMessages
from .unpinallforumtopicmessages import unpinAllForumTopicMessages
from .unpinallgeneralforumtopicmessages import unpinAllGeneralForumTopicMessages
from .unpinchatmessage import unpinChatMessage
from .update import Update
from .uploadstickerfile import uploadStickerFile
from .user import User
from .userchatboosts import UserChatBoosts
from .userprofilephotos import UserProfilePhotos
from .usersshared import UsersShared
from .venue import Venue
from .verifychat import verifyChat
from .verifyuser import verifyUser
from .video import Video
from .videochatended import VideoChatEnded
from .videochatparticipantsinvited import VideoChatParticipantsInvited
from .videochatscheduled import VideoChatScheduled
from .videochatstarted import VideoChatStarted
from .videonote import VideoNote
from .voice import Voice
from .webappdata import WebAppData
from .webappinfo import WebAppInfo
from .webhookinfo import WebhookInfo
from .writeaccessallowed import WriteAccessAllowed